name: CI/CD con Docker

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]  # activa también con versiones
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: pepebotella911/my-image

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Prometheus + Grafana
        run:{
        docker pull prom/prometheus
        docker pull grafana/grafana

    - name: Deploy containers
        run:{
        docker network create monitoring
        docker run -d --name prometheus --network monitoring prom/prometheus
        docker run -d --name grafana --network monitoring -p 3000:3000 grafana/grafana

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

