name: CI/CD con Docker

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]  # activa también con versiones
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: pepebotella911/my-image

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Scan image with Docker Scout
      uses: docker/scout-action@v1
      with:
        image: pepebotella911/my-image:latest
        dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
        command: scan
