name: Mantenimiento Automatizado

on:
  workflow_dispatch:
    inputs:
      tipo:
        description: 'Tipo de mantenimiento'
        required: true
        default: 'correctivo'

jobs:
  mantenimiento:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Login al registry GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convertir nombre de owner a minúsculas
      id: vars
      run: |
        echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Build y Push de versión corregida
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/app:${{ github.run_number }} .
        docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/app:${{ github.run_number }}

    - name: Mostrar tipo de mantenimiento
      run: echo "Mantenimiento tipo:${{ github.event.inputs.tipo }}"
