name: Mantenimiento Automatizado

on:
  workflow_dispatch:
    inputs:
      tipo:
        description: 'Tipo de mantenimiento'
        required: true
        default: 'correctivo'

jobs:
  mantenimiento:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Login a DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build y Push a DockerHub
      run: |
        docker build -t pepebotella911/app:${{ github.run_number }} .
        docker push pepebotella911/app:${{ github.run_number }}

    - name: Mostrar tipo de mantenimiento
      run: echo "Mantenimiento tipo:${{ github.event.inputs.tipo }}"
